version: 2
updates:
  # Check for major GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Check for direct Go Module updates
  - package-ecosystem: "go:modules"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
